---
# tasks file for hasicorp_vault
- name: Get Vault secret data
  uri:
    url: "https://10.0.0.184:8200/v1/ansible_containerized/data/ansible_credentials"
    method: GET
    headers:
      X-Vault-Token: "{{ token }}"
    validate_certs: false  # Use with caution in production!
    return_content: yes
  register: vault_result

- name: Set facts for each key/value pair
  set_fact:
    "{{ item.key | regex_replace('[-.]', '_') }}": "{{ item.value }}"  # Replace hyphens and periods with underscores, add prefix
  loop: "{{ vault_result.json.data.data | dict2items }}"  # Iterate through key/value pairs
  when: vault_result is defined and vault_result.json.data.data is defined