---
# This token is used to synchronise certifified and validated collections from
# console.redhat.com.
# To generate an AH token, go to the url:
# https://console.redhat.com/ansible/automation-hub/token and click on
# "Load Token" in the "Offline token" chapter.
cloud_token: 'eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI0NzQzYTkzMC03YmJiLTRkZGQtOTgzMS00ODcxNGRlZDc0YjUifQ.eyJpYXQiOjE3NDA3NzczODIsImp0aSI6IjU4ZDYxNjFmLWIxZGUtNDQ4Yi05MTVkLTU1YTRhNjU5ZjVhZSIsImlzcyI6Imh0dHBzOi8vc3NvLnJlZGhhdC5jb20vYXV0aC9yZWFsbXMvcmVkaGF0LWV4dGVybmFsIiwiYXVkIjoiaHR0cHM6Ly9zc28ucmVkaGF0LmNvbS9hdXRoL3JlYWxtcy9yZWRoYXQtZXh0ZXJuYWwiLCJzdWIiOiJmOjUyOGQ3NmZmLWY3MDgtNDNlZC04Y2Q1LWZlMTZmNGZlMGNlNjprZXJzbWFrYTMiLCJ0eXAiOiJPZmZsaW5lIiwiYXpwIjoiY2xvdWQtc2VydmljZXMiLCJub25jZSI6ImM1NTIyODc0LWNiZTUtNDVjOC1hZTEwLTVlZGRmYmZhYjU0MCIsInNpZCI6IjMxNDQ1ODVmLWQ0MDgtNDBjMi1iMDQ1LTI4ZjdjNWE5Y2UzOSIsInNjb3BlIjoib3BlbmlkIGJhc2ljIGFwaS5pYW0uc2VydmljZV9hY2NvdW50cyByb2xlcyB3ZWItb3JpZ2lucyBjbGllbnRfdHlwZS5wcmVfa2MyNSBvZmZsaW5lX2FjY2VzcyJ9.AmdfFW24YsPLhY7-CIY-50KHnJxCsM38p6V7QNXVZhJDmlBCWB75ZE4_rigouYC4LKld8XbOmzeoQCxwYRqvFA'

# This token use Red Hat's API to download AAP
# Generate this token here: https://access.redhat.com/management/api
# Keep in mind that the token will expire if it is not used for 30 days.
offline_token: 'eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI0NzQzYTkzMC03YmJiLTRkZGQtOTgzMS00ODcxNGRlZDc0YjUifQ.eyJpYXQiOjE3NDA3Nzc0MTIsImp0aSI6IjQzMmRiYzVjLWFiZTMtNGIxMS1hMTMyLTUxYTVlMzg2NjViNCIsImlzcyI6Imh0dHBzOi8vc3NvLnJlZGhhdC5jb20vYXV0aC9yZWFsbXMvcmVkaGF0LWV4dGVybmFsIiwiYXVkIjoiaHR0cHM6Ly9zc28ucmVkaGF0LmNvbS9hdXRoL3JlYWxtcy9yZWRoYXQtZXh0ZXJuYWwiLCJzdWIiOiJmOjUyOGQ3NmZmLWY3MDgtNDNlZC04Y2Q1LWZlMTZmNGZlMGNlNjprZXJzbWFrYTMiLCJ0eXAiOiJPZmZsaW5lIiwiYXpwIjoicmhzbS1hcGkiLCJzaWQiOiIzMTQ0NTg1Zi1kNDA4LTQwYzItYjA0NS0yOGY3YzVhOWNlMzkiLCJzY29wZSI6ImJhc2ljIHJvbGVzIHdlYi1vcmlnaW5zIGNsaWVudF90eXBlLnByZV9rYzI1IG9mZmxpbmVfYWNjZXNzIn0.RSIZ4Q-ka294Thhym2H4gpkIOCVf03QSikSqcvCekJMfZI0oZPduc9dfI-O0SnsKjjWyqv7ZoS2DJ9OGttopnw'

# Red Hat account login (this is used to attach your subs to controller)
rh_username: 'kersmaka3'

# Red Hat account password
rh_password: 'Anth2&32'

# The password for the root user on builder (using a non-root user would require
# further changes)
root_machine_pass: 'redhat'

# This is the password of the 'token_user' account that the playbook will create
# in the private Automation Hub.
ah_token_password: 'redhat'

# This is the password of the 'api_user' user that the playbook will create
# in the controller(s)
controller_api_user_pass: 'redhat'

# The admin password for the controller; if unspecified, the default
# is Password1234!
controller_pass: 'redhat'

# The admin password for the private Automation Hub; if unspecified, the default
# is Password1234!
ah_pass: 'redhat'

# The password to decrypt this vault
vault_pass: 'redhat'
...
